Coursera/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
]

courses/urls.py
from django.urls import path

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', LessonDetailView.as_view(), name='lesson_detail'),
]

users/urls.py
from django.urls import path

from users.views import Profile

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),

]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Bosh saxifa</a>
      <span>Biz haqimizda</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-danger'>Assalom alekum!</h1>
		    <h2>Biz haqimizda ko'proq ma'lumotga ega bo'ling</h2>
		    <hr>
		    <p>Undan keyin daromadning ortishi kuzatiladi, lekin u qandaydir buyuk asrning ishi bilan bir vaqtda sodir bo'ladi. Chunonchi, eng mayda tafsilotiga kelsak, hech kim biron bir ish bilan shug'ullanmasligi kerak, agar u o'ziga foyda keltirmasa.</p>
		    <p>Naslchilik yo'q degan umidda darddan tuk bo'lishni istaydi rohatda tanbehda darddan g'azablanma. Toki nafs ko‘r bo‘lmasa, chiqmaydi, burchini tashlab, qalbini yumshatuvchi aybdor, ya’ni mehnatdir.</p>
		    <button type="button" class="btn btn-danger">Ko'proq bilib olish</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">
<head>
	<title>IT Creative - Online Kurslar</title>
	<meta charset="UTF-8">
	<meta name="description" content="IT Creative ta'lim shabloni">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>



</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3">
					<div class="site-logo">
						<img src="{%static 'webuni/img/logo.png' %}" alt="">
					</div>
					<div class="nav-switch">
						<i class="fa fa-bars"></i>
					</div>
				</div>
				<div class="col-lg-9 col-md-9">
					{% if request.user.is_authenticated%}
					<li><a href="{% url 'users:profile' %}" class="site-btn header-btn">Boshqaruv : {{request.user.username}}</a></li>
					{% else %}
					<li><a href="{% url 'account_login' %}" class="site-btn header-btn">Hisobga kirish</a></li>
					{% endif %}
					<nav class="main-menu">
						<ul>
							<li><a href="{% url 'courses:home' %}">Bosh saxifa</a></li>
							<li><a href="{% url 'courses:about' %}">Biz haqimizda</a></li>
							<li><a href="{% url 'courses:course_list' %}">Kurslar</a></li>
							<li><a href="blog.html">Yangiliklar</a></li>
							<li><a href="{% url 'courses:contact' %}">A'loqa</a></li>
							{% if request.user.is_authenticated %}
              <li><a href="{% url 'account_logout' %}">Chiqish</a></li>
              {% endif %}
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- Header section end -->
{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}


	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Hozir bizning hamjamiyatimizga qo'shiling!</h2>
				<p>Mijoz juda muhim, mijozni mijoz kuzatib boradi. O'sha paytgacha dunyodagi eng buyuk mauris edi, ammo rasmiy veb-sayt yo'q edi. Shuningdek, huquqiy donolik. Kursning oxiri.</p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Hozir roʻyxatdan oʻtish</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Aloqa ma'lumotlari</h4>
						<ul class="contact-list">
							<li>O'zbekiston <br>Jizzax viloyati</li>
							<li>+998 97 521 66 86</li>
							<li>itcreative0071@gmail.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Muhandislik</h4>
						<ul>
							<li><a href="">Amaliy tadqiqotlar</a></li>
							<li><a href="">Kompyuter muhandisligi</a></li>
							<li><a href="">Dasturiy ta'minot muhandisligi</a></li>
							<li><a href="">Axborot muhandisligi</a></li>
							<li><a href="">Tizim muhandisligi</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Grafika dizayni</h4>
						<ul>
							<li><a href="">Amaliy tadqiqotlar</a></li>
							<li><a href="">Kompyuter muhandisligi</a></li>
							<li><a href="">Dasturiy ta'minot muhandisligi</a></li>
							<li><a href="">Axborot muhandisligi</a></li>
							<li><a href="">Tizim muhandisligi</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Dasturchilik</h4>
						<ul>
							<li><a href="">Amaliy tadqiqotlar</a></li>
							<li><a href="">Kompyuter muhandisligi</a></li>
							<li><a href="">Dasturiy ta'minot muhandisligi</a></li>
							<li><a href="">Axborot muhandisligi</a></li>
							<li><a href="">Tizim muhandisligi</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Eng so'ngi o'zgarishlar haqida</h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn">Obuna boʻlish</button>
							<p>* Biz spam yubormaymiz</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Foydalanish shartlari</a></li>
					<li><a href="#">Roʻyxatdan oʻtish</a></li>
					<li><a href="#">Maxfiylik</a></li>
				</ul>
				<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://github.com/xusanbek0071" target="_blank">IT Creative</a></div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script async src="https://relayv2-dev.s3.amazonaws.com/analytics/distrobird_widget.js" data-widget-uid="c97e3cb3-9d88-42cc-a467-9288c7075e84"></script>
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Bosh saxifa</a>
      <span>A'loqa</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Kursingizni qidiring</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Kurs nomi">
            <input type="text" class="last-m" placeholder="Turkum ">
            <button class="site-btn btn-dark">Kurs izlash</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Biz bilan a'loqa</h2>
            <p>Mijoz juda muhim, mijozni mijoz kuzatib boradi. O'sha paytgacha dunyodagi eng buyuk mauris edi, ammo rasmiy veb-sayt yo'q edi. Shuningdek, huquqiy donolik. </p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="Ismingiz">
            <input type="text" placeholder="E-mail manzilingiz">
            <input type="text" placeholder="Mavzu nimada">
            <textarea placeholder="Xabaringiz"></textarea>
            <button class="site-btn">Xabar yuborish</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Aloqa ma'lumotlari</h2>
            <p>O'sha paytgacha dunyodagi eng buyuk mauris edi, ammo rasmiy veb-sayt yo'q edi. Shuningdek, huquqiy donolik. U tomoq kursining oxirida to'xtatildi.</p>
          </div>
          <div class="phone-number">
            <span>To'g'ridan-to'g'ri a'loqa</span>
            <h2>+998 97 521 66 86</h2>
          </div>
          <ul class="contact-list">
            <li>Jizzax viloyati <br>Ravot QFY</li>
            <li>+9989 97 521 66 86</li>
            <li>itcreative0071@gmail.com</li>
          </ul>
          <div class="social-links">
            <a href="https://t.me/MBin_Dev_0071"><i class="fa fa-telegram"></i></a>
            <a href="https://m.facebook.com/suyunov.husanbek/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/it_creative0071/"><i class="fa fa-twitter"></i></a>
            {% comment %} <a href="#"><i class="fa fa-dribbble"></i></a> {% endcomment %}
            {% comment %} <a href="#"><i class="fa fa-behance"></i></a> {% endcomment %}
            <a href="https://github.com/xusanbek0071"><i class="fa fa-github"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      <h2>Eng yaxshi bepul onlayn kurslarni oling</h2>
      <p>Mijoz juda muhim, mijozni mijoz kuzatib boradi. O'sha vaqtga qadar, maurisquerusning eng katta maurisi edi, lekin hech qanday rutrum yo'q edi. Shuningdek, huquqiy donolik. Kursning oxiri.</p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form class="intro-newslatter">
          <input type="text" placeholder="Kurs nomi">
          <input type="text" class="last-s" placeholder="Turkumi">
          <button class="site-btn">Kurslarni izlash</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->


<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2>Bizning kurs toifalarimiz</h2>
      <p>Mijoz juda muhim, mijozni mijoz kuzatib boradi. O'sha paytgacha dunyodagi eng buyuk mauris edi, ammo rasmiy veb-sayt yo'q edi. Shuningdek, huquqiy donolik. Kursning oxiri.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{% static 'webuni/img/categories/1.jpg' %}"></div>
          <div class="ci-text">

            <h5>{{cat|capfirst}}</h5>

            <p>Lorem ipsum dolor sit amet, consectetur</p>
            <span>30 ta eng yaxshi kurslar</span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->

<!-- signup section -->
<section class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>O'qituvchi bo'lish uchun ro'yxatdan o'ting</h2>
            <p>Mijoz juda muhim, mijozni mijoz kuzatib boradi. O'sha paytgacha dunyodagi eng buyuk mauris edi, ammo rasmiy veb-sayt yo'q edi. Shuningdek, huquqiy donolik. Kursning oxiri.</p>
          </div>
          <!-- signup form -->
          <form class="signup-form">
            <input type="text" placeholder="Ismingiz" name="name">
            <input type="text" placeholder="E-Mail manzilingiz" name="e-mail">
            <input type="text" placeholder="Telefon raqamingiz" name="phone">
            <button class="site-btn">Yuborish</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- signup section end -->

{% endblock content %}